services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: market
      POSTGRES_INITDB_ARGS: "--data-checksums"

      # This optional variable can be used to control the auth-method for host connections for all databases, all users, and all addresses.
      # If unspecified then scram-sha-256 password authentication⁠ is used (in 14+; md5 in older releases).
      # On an uninitialized database, this will populate pg_hba.conf via this approximate line:
      # echo "host all all all $POSTGRES_HOST_AUTH_METHOD" >> pg_hba.conf

      # See the PostgreSQL documentation on pg_hba.conf⁠ for more information about possible values and their meanings.
      POSTGRES_HOST_AUTH_METHOD: trust
# -e PGDATA=/var/lib/postgresql/data/pgdata \
# -v /custom/mount:/var/lib/postgresql/data \
