services:
  postgres:
    container_name: postgres
    image: postgres:17.1
    restart: always
    build: postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: UserDB

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    # volumes:
    #   - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgdata:
